long_term_memory:
  derivative_deriver: sentence
  metadata_prefix: "[$source_timestamp] $producer_id: "
  embedder: my_embedder_id
  reranker: my_reranker_id
  vector_graph_store: my_storage_id

sessiondb:
  uri: sqlitetest.db

model:
  my_model_id:
    model_name: "gpt-4o-mini"
    api_key: "token-abc123"
storage:
  my_storage_id:
    vendor_name: neo4j
    host: localhost
    port: 7687
    user: neo4j
    password: "neo4j_password"
    force_exact_similarity_search: true

embedder:
  my_embedder_id:
    name: "openai"
    config:
      model: "Qwen/Qwen3-Embedding-0.6B"
      api_key: "token-abc123"
      base_url: "http://localhost:8001/v1"

reranker:
  my_reranker_id:
    type: "rrf-hybrid"
    reranker_ids:
      - id_ranker_id
      - bm_ranker_id
      - ce_ranker_id
  id_ranker_id:
    type: "identity"
  bm_ranker_id:
    type: "bm25"
  ce_ranker_id:
    type: "cross-encoder"
    model_name: "cross-encoder/qnli-electra-base"
